refactor: remove excess styles
facebookincubator/infima pull request #153
Opened 2021-07-13 08:35 UTC by lex111

A follow-up of #150

Basically, this is superfluous code that can be safely removed.

2021-07-14 14:29 UTC, slorber reviewed
I'm not about removing those styles, but it could have unintended side-effects in some places.

@yangshun any opinion?

2021-07-14 14:29 UTC, slorber commented on packages/core/styles/components/menu.pcss
> -    cursor: pointer;
Also assume that we apply that class to an anchor but it may not always be the case?

2021-07-14 14:30 UTC, slorber commented on packages/core/styles/components/button.pcss
> -    display: block;
+ the button is by default "inline-block".

This means `<button className="button button--block">` will now be inline block, that does not seem to be the purpose of this class

2021-07-14 23:28 UTC, lex111 commented on packages/core/styles/components/button.pcss
> -    display: block;
And yes and no, it seems to me that "block" in this case points more to full-width rather then `display:block` declaration.

2021-07-14 23:29 UTC, lex111 commented on packages/core/styles/components/menu.pcss
> -    cursor: pointer;
The point is that this class always applies to links that already have cursor pointer by default

2021-07-15 19:05 UTC, yangshun requested changes
I don't think we should be removing these. I'm not confident it won't change things. Sometimes even though the styles are present in the default browser styling, we want to be defensive and still apply these styles. I'm also not convinced we did thorough testing to ensure nothing broke. A lot of these styles were written by referencing GitHub and Bootstrap's CSS and they are probably there for good reason, maybe for some legacy browser or something. I think the risk is not worth it.

2021-07-15 19:56 UTC, lex111 reviewed
As always, I want to make sure that we use styles we _really_ need for elements. For example, why would we want to set styles that essentially duplicate the browser ones? There's actually very low risk here. That's why I've commented on each change in this PR, hopefully to convince you that removing those styles won't break anything.

2021-07-15 19:56 UTC, lex111 commented on packages/core/styles/content/image.pcss
> -  box-sizing: content-box;
Why is it necessary for images? Is there use case for this?

2021-07-15 19:56 UTC, lex111 commented on packages/core/styles/content/image.pcss
> -  border-style: none;
This was relevant for IE9, but we don't even support IE11. So why this declaration?

2021-07-15 19:56 UTC, lex111 commented on packages/core/styles/components/navbar.pcss
> -    text-decoration: none;
We have `text-decoration:none` by default for all links, which is completely unnecessary (see https://github.com/facebookincubator/infima/blob/master/packages/core/styles/content/typography.pcss#L11).

2021-07-15 19:56 UTC, lex111 commented on packages/core/styles/components/navbar.pcss
> -    position: relative;
Leftover from already removed code when we used absolute positioning inside dropdown.

2021-07-15 19:56 UTC, lex111 commented on packages/core/styles/components/navbar.pcss
> -    cursor: pointer;
This is default declaration for links in all browsers, why do we need to duplicate it?

2021-07-15 19:56 UTC, lex111 commented on packages/core/styles/components/navbar.pcss
> -  width: 100%;
For `navbar__inner` we already set width to 100%, so there is absolutely no need to set full width for parent `navbar` element.

2021-07-15 19:56 UTC, lex111 commented on packages/core/styles/components/button.pcss
> -    display: block;
All right, will revert this.

2021-07-15 19:56 UTC, lex111 commented on packages/core/styles/content/table.pcss
> -  width: 100%;
For tables we use block model, so `width:100%` makes no sense, since tables will not be full width by default. If we want tables to stretch to full width (100%) always, we need to remove `display:block`. What should we do then?

2021-07-15 19:56 UTC, lex111 commented on packages/core/styles/content/typography.pcss
> -  overflow: hidden;
Styles for `<hr>` scare me. Why are there so many unnecessary styles? If you remove them, nothing will change anyway. Even Bootstrap doesn't have that:

```
hr {
  margin: 1rem 0;
  color: inherit;
  background-color: currentColor;
  border: 0;
  opacity: 0.25;
}
```

2021-07-16 10:15 UTC, slorber commented
From my perspective, removing styles represent a breaking change, and risk, and has a minor ROI value for the end-users (perf micro-optimization). In general, I'd like to avoid such changes unless it's fixing an existing problem user reported.

However if styles are inspired by Bootstrap (which I didn't know) and Bootstrap decided later to remove some unused style because it's not unnecessary, I'm not against removing those styles as well, as it seems a safe thing to do (same ROI, less risk)

2021-07-24 15:52 UTC, lex111 commented
I'm sure that's not the case, the current changes will not affect users websites, as I wrote above in my review, these are useless styles.

2021-07-27 09:21 UTC, slorber approved these changes
Going to approve this, feel free to merge it
Not agreeing 100% with all the changes, but they seem safe enough.

Still think this kind of PR is complicated to handle for reviewers (risky, time-consuming, little ROI), so I'd prefer to not have too much of them in the future 😅

2021-07-27 09:21 UTC, slorber commented on packages/core/styles/components/menu.pcss
> -    cursor: pointer;
There's no guarantee that users will apply that class to only anchors, but this is also unlikely so it should be fine

2021-07-27 09:21 UTC, slorber commented on packages/core/styles/components/navbar.pcss
> -  width: 100%;
ok for me

2021-07-27 09:21 UTC, slorber commented on packages/core/styles/components/navbar.pcss
> -    cursor: pointer;
this is the default for anchors, but users may do things that you don't expect (on their homepage or other places), like `<div className=menu__link">` and those users would be affected. It's a common practice to try to make non-link elements look like links.

Unlikely to be the case so let's remove it anyway

2021-07-27 09:21 UTC, slorber commented on packages/core/styles/components/navbar.pcss
> -    position: relative;
👍

2021-07-27 09:21 UTC, slorber commented on packages/core/styles/components/navbar.pcss
> -    text-decoration: none;
same as cursor: pointers, assumes class is always applied to an anchor. But seems fine to remove

2021-07-27 09:21 UTC, slorber commented on packages/core/styles/content/image.pcss
> -  border-style: none;
👍

2021-07-27 09:21 UTC, slorber commented on packages/core/styles/content/image.pcss
> -  box-sizing: content-box;
👍

2021-07-27 09:21 UTC, slorber commented on packages/core/styles/content/table.pcss
> -  width: 100%;
Not sure to understand but this removal seems fine

2021-07-27 09:21 UTC, slorber commented on packages/core/styles/content/typography.pcss
> -  overflow: hidden;
👍

2021-07-27 10:56 UTC, merged