Make breadcrumb links without `href` not have hover styles
facebookincubator/infima pull request #266
Opened 2022-06-25 18:54 UTC by srmagura

Breadcrumb items do not necessarily have an `href`, but they always change color when the user hovers over them. The hover styles give the impression that the breadcrumb item is a clickable link even if this is not the case.

This can be seen in the [Redux documentation](https://redux.js.org/tutorials/essentials/part-1-overview-concepts) — neither "Tutorials" nor "Redux Essentials" are links, yet they have hover styles.

This PR uses the `:link` pseudoselector to fix this.

2022-06-30 08:39 UTC, slorber requested changes
Agree this UX is not ideal and we should change it.

> Breadcrumb items do not necessarily have an href, but they always change color when the user hovers over them. 

In practice it's more:

> breadcrumb items might be simple `<span>` instead of `<a>` when we don't have a link

Not 100% sure using `:link` is the solution here?

---

Also worth adding a test to our demo page here: https://deploy-preview-266--infima.netlify.app/demo/

We only have breadcrumb items with links currently (unlike what we have on the Docusaurus side in practice). Please try to add something here that helps reviewing the current PR.

2022-06-30 08:39 UTC, slorber commented on packages/core/styles/components/breadcrumb.pcss
> +    &:link:hover {
> The :link CSS pseudo-class represents an element that has not yet been visited.

Does it mean that we'll lose the hover effect once the link is visited? 😅 

Maybe using `:is(a):hover` would be better? (90% support good enough for this usecase)

TIL there's also an `:any-link` pseudo-selector, looks like a potential good fit?

2022-06-30 08:39 UTC, slorber commented on packages/core/styles/content/typography.pcss
> +  &:link:hover {
🤷‍♂️ this one looks more general and not sure it's directly related to your problem, considering the element is already a `<a>` there?

Can it have unwanted side effects? + not sure `:link` is what we want anyway

2022-07-05 13:20 UTC, srmagura commented on packages/core/styles/content/typography.pcss
> +  &:link:hover {
You can have `<a>` elements that don't represent links (like headings). It usually only makes sense to display hover styles if the `<a>` represents a link.

2022-07-05 13:22 UTC, srmagura commented
Thanks for the feedback. I switched to `:any-link` and added an example.

> breadcrumb items might be simple <span> instead of <a> when we don't have a link

True, but I assume you would not want hover styles if the breadcrumb item is a `<span>`, correct?

2022-07-05 13:38 UTC, Josh-Cena commented
```diff
  diff --git a/packages/core/dist/css/default/default.css b/packages/core/dist-branch/css/default/default.css
  index 95fc6e3..f258e29 100644
  --- a/packages/core/dist/css/default/default.css
  +++ b/packages/core/dist-branch/css/default/default.css
  @@ -1233,[7](https://github.com/facebookincubator/infima/runs/7197269101?check_suite_focus=true#step:4:7) +1233,25 @@ a {
     transition: color var(--ifm-transition-fast) var(--ifm-transition-timing-default);
   }
  
  -a:hover {
  +a:link:hover, a:visited:hover {
  +    color: var(--ifm-link-hover-color);
  +    /* autoprefixer: ignore next */
  +    text-decoration: var(--ifm-link-hover-decoration);
  +  }
  +
  +a:-webkit-any-link:hover {
  +    color: var(--ifm-link-hover-color);
  +    /* autoprefixer: ignore next */
  +    text-decoration: var(--ifm-link-hover-decoration);
  +  }
  +
  +a:-moz-any-link:hover {
  +    color: var(--ifm-link-hover-color);
  +    /* autoprefixer: ignore next */
  +    text-decoration: var(--ifm-link-hover-decoration);
  +  }
  +
  +a:any-link:hover {
       color: var(--ifm-link-hover-color);
       /* autoprefixer: ignore next */
       text-decoration: var(--ifm-link-hover-decoration);
  @@ -172[8](https://github.com/facebookincubator/infima/runs/7197269101?check_suite_focus=true#step:4:8),7 +1746,22 @@ hr {
       transition-timing-function: var(--ifm-transition-timing-default);
     }
  
  -.breadcrumbs__link:hover {
  +.breadcrumbs__link:link:hover, .breadcrumbs__link:visited:hover, area.breadcrumbs__link[href]:hover {
  +      background: var(--ifm-breadcrumb-item-background-active);
  +      text-decoration: none;
  +    }
  +
  +.breadcrumbs__link:-webkit-any-link:hover {
  +      background: var(--ifm-breadcrumb-item-background-active);
  +      text-decoration: none;
  +    }
  +
  +.breadcrumbs__link:-moz-any-link:hover {
  +      background: var(--ifm-breadcrumb-item-background-active);
  +      text-decoration: none;
  +    }
  +
  +.breadcrumbs__link:any-link:hover {
         background: var(--ifm-breadcrumb-item-background-active);
         text-decoration: none;
       }
  ```

2022-07-05 13:44 UTC, srmagura commented
@Josh-Cena Why are those changes necessary? I tested in Chrome, Safari, and Firefox and the vendor prefixes were not necessary.

2022-07-05 13:45 UTC, Josh-Cena commented
Ah, no, that's the "post diff comment" workflow's result 😄 It can't be posted on PRs created from forks, so I manually post it so we know how the distributed CSS has changed. See https://github.com/facebookincubator/infima/pull/255#issuecomment-1120486531 for example.

2022-07-05 13:47 UTC, srmagura commented
Ooooohhhhh, OK. Do I need to do anything to get that workflow to pass?

2022-07-05 13:50 UTC, Josh-Cena commented
No, it's a problem with our workflow plus some permission quirks. It's mostly okay this way.

2022-07-06 16:12 UTC, slorber commented
LGTM thanks 👍

2022-07-06 16:13 UTC, slorber commented on packages/core/styles/components/breadcrumb.pcss
> +    &:link:hover {
yes, not very intuitive 😅

2022-07-06 16:15 UTC, merged

2022-07-09 01:47 UTC, pranabdas commented on packages/core/styles/content/typography.pcss
>      text-decoration: var(--ifm-link-hover-decoration);
I guess this is causing `text-decoration: underline` for all links including buttons, sidebar menu, navbar, navbar dropdown menu. https://github.com/facebook/docusaurus/issues/7748

2022-07-09 02:17 UTC, yangshun commented on packages/core/styles/content/typography.pcss
>      text-decoration: var(--ifm-link-hover-decoration);
I think adding this pseudo selector increases the specificity

2022-07-09 02:33 UTC, srmagura commented on packages/core/styles/content/typography.pcss
>      text-decoration: var(--ifm-link-hover-decoration);
Thanks for pointing this out.

https://github.com/facebookincubator/infima/pull/267