feat: expand container width on large screen
facebookincubator/infima pull request #62
Opened 2021-02-02 13:35 UTC by lex111

I think we can borrow this technique from Bootstrap.

Jest blog (need to resize columns as 3/7/2):

| Before   | After    |
| -------- | -------- |
| ![image](https://user-images.githubusercontent.com/4408379/106607228-1f429100-6574-11eb-9e84-54df923ba14d.png) | ![image](https://user-images.githubusercontent.com/4408379/106607266-2bc6e980-6574-11eb-8c6c-1507bb3cf036.png) |

Docs:

| Before   | After    |
| -------- | -------- |
| ![image](https://user-images.githubusercontent.com/4408379/106607397-5153f300-6574-11eb-9235-f0ca070a16bd.png) | ![image](https://user-images.githubusercontent.com/4408379/106607364-44cf9a80-6574-11eb-91b5-09d0858ea46e.png) |

2021-02-02 17:01 UTC, slorber commented
Thanks, That looks better to me.

Was wondering if it's not worth keeping the content perfectly centered? (not even sure it is right now 😅 )

2021-02-02 17:06 UTC, lex111 commented
Actually not, but maybe I don't properly understand what you mean.

2021-02-02 18:29 UTC, slorber commented
For example:

![image](https://user-images.githubusercontent.com/749374/106645538-c92e1780-658c-11eb-90ee-617d66045012.png)


I mean we may want the main content to have the same margin on the right and left sides, is using 2/8/2 or 3/6/3 and not 1/8/3  

I'm not a designer so not sure what is a good choice here 😅  

Increasing the container width for larger screens looks safe to me, but can't really tell for moving to `3/7/2` as it's a design decision

2021-02-02 18:33 UTC, lex111 commented
Well, it might be worth discussing this with other team members later.

Changing columns to `3/7/2` applies only to blog pages, this is necessary to increase the block size with recent posts.

2021-02-08 19:40 UTC, yangshun commented
I'll review this

2021-02-19 15:51 UTC, yangshun requested changes

2021-02-19 15:51 UTC, yangshun commented on packages/core/styles/layout/grid.css
> +      --ifm-container-width: 1320px;
We should give people a way to modify this just by tweaking CSS variables. If we do this then they have to write a new media query. I think we should define a CSS variable for this viewport so people can override it if they want to:

```
--ifm-container-width: 1140px;
--ifm-container-width-xl: 1320px;

...

 @media (min-width: 1440px) {
    & {
      max-width: var(--ifm-container-width-xl);
    }
}
```

2021-02-19 17:10 UTC, lex111 commented on packages/core/styles/layout/grid.css
> +      --ifm-container-width: 1320px;
Thanks, fixed.

2021-02-19 18:41 UTC, slorber commented
For some weird reason I see this change applied to the demo page, but not the infima website deploy preview 😅  any idea why?

Also, I think it's an improvement, but don't like too much having containers "jump size" after a certain threshold. What if the container would just grow naturally between 1200px and 1440px, using a % value?

2021-02-19 18:59 UTC, lex111 commented
> Also, I think it's an improvement, but don't like too much having containers "jump size" after a certain threshold. What if the container would just grow naturally between 1200px and 1440px, using a % value?

What do you have in mind exactly? Can you show the code for implementing this? Normally, the screen has a fixed size, so I don't understand how container can jump in this case, unless you manually change screen size, for example, for development purposes.

2021-02-20 03:32 UTC, yangshun approved these changes
Nice one, thank you!

2021-02-20 03:34 UTC, yangshun commented
> For some weird reason I see this change applied to the demo page, but not the infima website deploy preview 😅 any idea why?

Is the website deploy preview using the trunk version of Infima? Otherwise it won't show up there.

2021-02-20 03:34 UTC, merged

2021-02-22 14:27 UTC, slorber commented
> Is the website deploy preview using the trunk version of Infima? Otherwise it won't show up there.

Everything is using symlinks and I can see the changes locally so not sure what is happening with the deployed preview 😅 
Will see on next changes if it works or not but it is supposed to deploy the infima changes on the website

2021-02-22 14:36 UTC, slorber commented
> What do you have in mind exactly? Can you show the code for implementing this? Normally, the screen has a fixed size, so I don't understand how container can jump in this case, unless you manually change screen size, for example, for development purposes.

I mean, if the width is 1439px, do we really want the container to be significantly smaller than for width=1440px?

I do agree that resizing is not something done by regular users too much and the experience does not matter much, just saying that there's a way to optimize the width we render to for "middle width" devices by using a % value. Like `if width > 1300px && width < 1440px ) container-width=90%`. 

Not too important for now

2021-03-04 15:15 UTC, slorber commented
@lex111 do we want an even larger container for larger screens?

Jest reported truncated TOC:
https://jestjs.netlify.app/docs/mock-function-api

Even using the new xl container width it gets truncated for very large screens and feels like we are wasting some space.

![image](https://user-images.githubusercontent.com/749374/109982811-8b92ea80-7d02-11eb-87e7-c867a08d20ae.png)

2021-03-04 16:43 UTC, lex111 commented
@slorber it's hard to say, maybe in the docs layout we should adopt columns similar structure as in the blog?